### ISSUE TITLE
Would be good if you could provide screenshots of the different screens/pages of openvm

### ISSUE THREAD

**Issue by CheyenneForbes** [PenningDevelopment/openVM#4]

**Comment by Shackelford-Arden** [comment]
I agree! What kind of screen shots would you want to see?

**Comment by CheyenneForbes** [comment]
any kind that shows how it looks in a browser

**Comment by Shackelford-Arden** [comment]
@CheyenneForbes  Looks like @matthewalanpenning  added some screen shots for you on the main page :) I was going to throw some in here but he beat me to it...

**Comment by CheyenneForbes** [comment]
If you dont mind me asking, what is the set up used for the host machine in the screenshots? RAM, Processor, Storage, Vendor, etc.

**Comment by matthewalanpenning** [comment]
yes, I did add some screenshots now. I have been testing the software on Dell R510, R710s, and R810s because that is what I have to work with. They range anywhere from 16GB of RAM to 100+. Procressors are either Intel dual core, quad core or 6-core with multiple sockets, and Storage is usually in a RAID array. 

Also I have it running on a Digital Ocean droplet. Hope that helps.
